### ISSUE TITLE
Lands bug?

### ISSUE THREAD

**Issue by NoHoPeLess** [RHazDev/BlockRegenerator#7]
Hello have the following error using:

- Spigot 1.15.2-R0.1
- BlockRegen v3.4
- BlockRegen-Lands v3.4
- CoreProtect v2.18.1
- Lands 4.5.2.1

i create an land build for test purpose something, delete the land (now its wilderness) and nothing happend...? it dont regen to the default region...

Test-config: (fast timings for test purpose)

```
tasks:
  main:
    paused: false
    regen-delay: "30 seconds"

    alert:
      before: "&aRegeneration in 10 seconds..."
      before-delay: "10 seconds"
      after: "&aRegeneration done!"

    min-time: "2 minutes"
    amount: 100
    efficiency: 90
    radius: 64
    safe-radius: 2

    filters:
      worlds:
        enabled: true
        type: whitelist
        list:
          - world
          - world_nether
          - world_the_end
      materials:
        enabled: true
        type: blacklist
        list:
          - bedrock
          - "minecraft:chest"
      lands:
        enabled: true
        type: whitelist
        list:
          - wilderness
```

hope for any help here
